<?php

namespace Catalogue\CatalogueBundle\Entity;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends \Doctrine\ORM\EntityRepository
{
    //offre courant
    public function offrescourant()
    {
        $now = new \DateTime();
        $now = $now->format('Y-m-d h:m:s');
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where("u.dateDebut <= :date")
            ->andWhere("u.dateFin > :date")
            ->andWhere(' u.active = :a')
            ->orderBy('u.id')
            ->setParameter('date', $now)
            ->setParameter('a', 1);
        return $qb->getQuery()->getResult();
    }
    //find active offre findactiveoffre
    public function findactiveoffre()
    {

        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->andWhere(' u.active = :a')
            ->orderBy('u.id','DESC')
            ->setParameter('a', 1);
        return $qb->getQuery()->getResult();
    }
}
