<?php

namespace Catalogue\CatalogueBundle\Entity;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    //lister les produit par categorie
    public function byCategorie($categorie)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.categorie = :categorie')
            ->orderBy('u.id')
            ->setParameter('categorie', $categorie);
        return $qb->getQuery()->getResult();
    }
    //find active offre findactiveoffre
    public function findactiveoffre()
    {

        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->andWhere(' u.active = :a')
            ->orderBy('u.id','DESC')
            ->setParameter('a', 1);
        return $qb->getQuery()->getResult();
    }

}
