services:
#    utilisateur.example:
#        class: Catalogue\UtilisateurBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    login_listener:
          class: 'Catalogue\UtilisateurBundle\Listener\LoginListener'
          arguments: ['@fos_user.user_manager']
          tags:
              - { name: 'kernel.event_listener', event: 'security.interactive_login' }
              - { name: 'kernel.listener', event: 'fos_user.security.implicit_login' }