services:
#    catalogue.example:
#        class: Catalogue\CatalogueBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
#services:
#    redirectionListener:
 #         class: Catalogue\CatalogueBundle\Listener\RedirectionListener
  #        arguments: [@service_container,@session]
   #       tags:
    #        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }